[package]
org = "qhana"
name = "qhana_backend"
version = "0.1.0"
distibution = "slbeta3"
export = ["qhana_backend", "qhana_backend.database"]

[[platform.java11.dependency]]
artifactId="sqlite-jdbc"
version="3.36.0.1"
groupId="org.xerial"

[[platform.java11.dependency]]
artifactId="mariadb-java-client"
groupId="org.mariadb.jdbc"
version="2.7.4"

[build-options]
observabilityIncluded = true
