[qhana.qhana_backend]

# Allow all CORS requests from any domain
corsDomains = ["*"]

[qhana.qhana_backend.internalUrlMap]
"localhost:5000" = "host.docker.internal:5000"
"localhost:5005" = "host.docker.internal:5005"

[qhana.qhana_backend.database]
# The config key must be present or ballerina crashes
