services:
  backend:
    build: .
    image: qhana-backend
    volumes:
      - ./experimentData:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      QHANA_URL_MAPPING: '{"(?<=^|https?://)localhost(:[0-9]+)?": "host.docker.internal$$1"}'
      QHANA_DB_TYPE: 'mariadb'
      QHANA_DB_HOST: 'db:3306'
      QHANA_DB_NAME: 'QHAnaExperiments'
      QHANA_DB_USER: 'qhana'
      QHANA_DB_PASSWORD: 'qhana'
      WAIT_HOSTS: 'db:3306'
    ports:
      - 9090:9090
    depends_on:
      - db
  db:
    image: "mariadb:10"
    volumes:
      - ./mariadb-schema.sql:/docker-entrypoint-initdb.d/mariadb-schema.sql
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: 'QHAnaExperiments'
      MARIADB_ROOT_PASSWORD: 'qhana_root'
      MARIADB_USER: 'qhana'
      MARIADB_PASSWORD: 'qhana'
